### ISSUE TITLE
Update repository

### ISSUE THREAD

**Issue by HummelN7872** [industrial-edge/pingpong-nodejs#2]
Please upate the repository same way like the other ping pong examples:

- https://github.com/industrial-edge/pingpong-python
- https://github.com/industrial-edge/pingpong-csharp
- https://github.com/industrial-edge/pingpong-c

**Comment by HummelN7872** [comment]
@EvaKaul could you please update the example

**Comment by EvaKaul** [comment]
@HummelN7872  done
